version: "3.4"
services:
  auth:
    build:
      dockerfile: systems/auth/Dockerfile
      context: .
    volumes:
      - ./systems/auth:/app
    command: /bin/bash -c "rm -f /app/tmp/pids/server.pid && /app/bin/rails s -b 0.0.0.0"
    depends_on:
      - db
      - kafka
    ports:
      - "8080:3000"
  tasks:
    build:
      dockerfile: systems/tasks/Dockerfile
      context: .
    volumes:
      - ./systems/tasks:/app
    command: /bin/bash -c "rm -f /app/tmp/pids/server.pid && /app/bin/rails s -b 0.0.0.0"
    depends_on:
      - db
      - kafka
      - auth
    ports:
      - "8081:3000"
    env_file:
      - ./systems/tasks/.env
  tasks-karafka:
    build:
      dockerfile: systems/tasks/Dockerfile
      context: .
    volumes:
      - ./systems/tasks:/app
    command: /bin/bash -c "bundle exec karafka s"
    depends_on:
      - db
      - kafka
    env_file:
      - ./systems/tasks/.env
  billing:
    build:
      dockerfile: systems/billing/Dockerfile
      context: .
    volumes:
      - ./systems/billing:/app
    command: /bin/bash -c "rm -f /app/tmp/pids/server.pid && /app/bin/rails s -b 0.0.0.0"
    depends_on:
      - db
      - kafka
      - auth
    ports:
      - "8082:3000"
    env_file:
      - ./systems/billing/.env
  billing-karafka:
    build:
      dockerfile: systems/billing/Dockerfile
      context: .
    volumes:
      - ./systems/billing:/app
    command: /bin/bash -c "bundle exec karafka s"
    depends_on:
      - db
      - kafka
    env_file:
      - ./systems/billing/.env
  db:
    image: "postgres:11.2"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=auth
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "10800:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
volumes:
  db-data: